env:
  es2021: true
  node: true
extends:
  - eslint-config-vscode-ext
  - standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: tsconfig.json
rules: {
  '@typescript-eslint/no-empty-function': 0,
  '@typescript-eslint/explicit-function-return-type': 0,
  '@typescript-eslint/strict-boolean-expressions': 0,
}
